name: update-companies-data
on:
  schedule:
    # Runs "at 18:45 (Nepal Time), every Monday to Friday
    - cron: "0 13,14,15,16,17 * * 0,1,2,3,4,5"
  workflow_dispatch:
permissions:
  contents: write
defaults:
  run:
    working-directory: ./src
jobs:
  update-daily-data:
    name: update-daily-data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10" # Version range or exact version of a Python version to use, using SemVer's version range syntax
      - name: Install packages
        run: pip install -r requirements.txt
      - name: Run updater
        run: python dailyDataScrapper.py
      - name: Setup Git
        run: git config --local user.email "sumeedimarahatta@gmail.com" && git config --local user.name "socialvegan101"
      - name: Commit Files
        run: git add ../data && git commit -m "Update data"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
